### ISSUE TITLE
iP Follow-up

### ISSUE THREAD

**Issue by kexiaowen** [bernicechio/duke#8]
@bernicechio Hi Bernice, all your iP peer reviewers reported that they could not get the JAR file to work. This is because you did not include the jar file in your release.
<img width="728" alt="Capture1" src="https://user-images.githubusercontent.com/20796648/67137813-a4197680-f26d-11e9-94c2-dc0bb6a8fc59.PNG">

This means we are unable to grade your iP. Please release a new version including a jar file that is cross-platform and confirmed to work with Java 11. When it is ready, post here to let me know ASAP (preferably by this weekend). Your release should look something like this:
<img width="392" alt="Capture2" src="https://user-images.githubusercontent.com/20796648/67137820-beebeb00-f26d-11e9-9a45-37feb2f498ff.PNG">

**Comment by bernicechio** [comment]
Hi Xiaowen, I have released the jar file.
